workspace:
  base: /go
  path: src/github.com/kontena/pharos-host-upgrades

pipeline:
  test:
    image: golang:1.10
    commands:
      - curl -L -o /tmp/dep-linux-amd64 https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && install -m 0755 /tmp/dep-linux-amd64 /usr/local/bin/dep
      - apt-get update && apt-get install -y libsystemd-dev
      - dep ensure -vendor-only
      - go test -v ./...

  # build and deploy quay.io/kontena/pharos-host-upgrades:edge from master branch
  docker-edge:
    registry: quay.io
    image: plugins/docker
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/pharos-host-upgrades
    tags: edge
    when:
      branch: master

  # build and deploy quay.io/kontena/pharos-host-upgrades:latest from master branch tags
  docker:
    registry: quay.io
    image: plugins/docker
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/pharos-host-upgrades
    auto_tag: true
    when:
      event: tag
